### ISSUE TITLE
JS Lint your code!

### ISSUE THREAD

**Issue by phlco** [johnnypacia/project-1#2]
Hiya! I just ran your code through http://www.jshint.com

It can give you some helpful warnings about things to correct

Here's the output with the line numbers and problems.  See if any of these help!

```
One warning
1 Missing semicolon.
```

**Comment by johnnypacia** [comment]
What version of code is this checking? Is there a way to see what line is missing a semicolon?

**Comment by phlco** [comment]
Good question! This is running the version of code I could get online, which is what you push to github.

The line number is `1` and the problem is missing semicolon.

**Comment by johnnypacia** [comment]
Ok I see,  the 1 there must mean line number 1. Thanks for the heads up!
