### ISSUE TITLE
Git Cloning Question

### ISSUE THREAD

**Issue by johnnypacia** [johnnypacia/project-1#3]
I know it's possible to clone our git repositories to multiple computers, but I wanted to ask whether that would be okay for working on this project. Sorry if this is an obvious question, I just want to make sure I knew the protocol before I did anything.

**Comment by annarankin** [comment]
Hi Johnny! As long as you make sure your code is up-to-date with your Github repo, you should be fine. Just be wary of making changes locally on one computer, then not pushing them up/pulling them down onto the other.

**Comment by johnnypacia** [comment]
Thank you, Anna!
